#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=15
set FILEDATE="12 February 2010"
set VERSION="1.1"
set TITLE='Time Response for State Space Models'
set SHORT_TITLE='Time Response' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh
