#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=15
set FILEDATE="12 February 2010"
set VERSION="1.3"
set TITLE='Transforms  and Time Responses of State Space Models'
set SHORT_TITLE='Transforms and Response' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh
