#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=01
set FILEDATE="February 2010"
set VERSION="1.2"
set TITLE='Introduction to Digital Systems'
set SHORT_TITLE='Introduction' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh

