#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=12
set FILEDATE="11th February 2010"
set VERSION="1.2"
set TITLE='Introduction to Digital Control'
set SHORT_TITLE='Digital Control (Intro)' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh
