#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=12
set FILEDATE="5th March 2015"
set VERSION="1.3"
set TITLE='Continuous System Equivalence'
set SHORT_TITLE='Continuous System Equivalence' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh
