#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=02
set FILEDATE="February 2010"
set VERSION="1.2"
set TITLE='Digital System Models and System Response'
set SHORT_TITLE='Models and Response' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh
