#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=16
set FILEDATE="12 February 2010"
set VERSION="1.2"
set TITLE='Canonical Forms'
set SHORT_TITLE='Canonical Forms' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh
