#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=16
set FILEDATE="24 March 2015"
set VERSION="1.3"
set TITLE='Canonical Forms'
set SHORT_TITLE='Canonical Forms' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh
