#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=13
set FILEDATE="12 February 2010"
set VERSION="1.2"
set TITLE='State-Space Models'
set SHORT_TITLE='' # $z would be interpreted by the shell
set RIGHT="${TITLE}"


source ../../process.tcsh


