#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=21
set FILEDATE="16 February 2010"
set VERSION="1.0"
set TITLE='State Observers'
set SHORT_TITLE='State Observers' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh
