#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=11
set FILEDATE="3rd March 2015"
set VERSION="1.3"
set TITLE='Digital System Models and System Response'
set SHORT_TITLE='Models and Response' # $z would be interpreted by the shell
set RIGHT="${SHORT_SECTION}: ${SHORT_TITLE}"

source ../../process.tcsh
