#!/bin/tcsh

source ../../course.tcsh
source ../section.tcsh
set LNO=14
set FILEDATE="13 March 2015"
set VERSION="1.3"
set TITLE='State-Space Models'
set SHORT_TITLE='' # $z would be interpreted by the shell
set RIGHT="${TITLE}"


source ../../process.tcsh
